"""first migration

Revision ID: 78dd70ac2960
Revises: 
Create Date: 2024-08-15 19:36:48.824813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78dd70ac2960'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_address', sa.String(), nullable=False),
    sa.Column('server_port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('encryption', sa.String(), nullable=True),
    sa.Column('security', sa.String(), nullable=True),
    sa.Column('network_type', sa.String(), nullable=True),
    sa.Column('header_type', sa.String(), nullable=True),
    sa.Column('header_host', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('UserDetail',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('Cart',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['UserDetail.user_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_table('v2ray_config',
    sa.Column('plan_name', sa.String(), nullable=True),
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(), nullable=False),
    sa.Column('config_email', sa.String(), nullable=False),
    sa.Column('traffic_gb', sa.Float(), nullable=True),
    sa.Column('period_day', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['UserDetail.user_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Product.product_id'], ),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('config_email'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('cart_v2ray_config_association',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['Cart.cart_id'], ),
    sa.ForeignKeyConstraint(['config_id'], ['v2ray_config.config_id'], ),
    sa.PrimaryKeyConstraint('cart_id', 'config_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_v2ray_config_association')
    op.drop_table('v2ray_config')
    op.drop_table('Cart')
    op.drop_table('UserDetail')
    op.drop_table('Product')
    # ### end Alembic commands ###
