"""first

Revision ID: b63cc43b7d45
Revises: 2c5268ee8525
Create Date: 2024-10-18 15:21:13.530481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63cc43b7d45'
down_revision: Union[str, None] = '2c5268ee8525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('plan_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'plan_name')
    # ### end Alembic commands ###
